# Generated by Django 4.0.4 on 2022-08-07 23:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='image',
            field=models.ImageField(default='default.jpg', upload_to='img/'),
        ),
        migrations.AddField(
            model_name='post',
            name='link',
            field=models.CharField(default='#', max_length=1000),
            preserve_default=False,
        ),
    ]
